sudo: true
language: node_js
branches:
  only:
  - master
before_script:
- sudo apt-get update
- sudo apt-get install imagemagick
- sudo apt-get install graphicsmagick
- bash ./bin/prepare.sh
script:
- ls -al img/photo.jpg
after_success: bash ./bin/deploy.sh
env:
  global:
    - GH_REF: github.com/miya0001/vrphoto.git
    - secure: "eXzYJf/ATwNRF2n2OC4qQi5EBRiOqnelCQgVrlYzH2Su9TCS4E4xW7sQQNu3s+ni5V1kE6wn/4ZniJB5jkXv9jLHH88OXINx5TbV4pquh/uj/zWdOIG+2//dPfJND8i/+ZuUC5emO3U7iUelZsqHzXLirA0iG/8FVC2qzsjRmtBao65BlNQgvYUYgQdmdOX37Rmhm3t0SEx2bzSTG6MEsjEjc3z2CSVeB7GT3KWBUqtU8Nq6ktgsIBAzdAwAPOrsJ9svKGOmlD9tGKKwYbIrFsgZu/IX9aXuHF1+XvwgOlaOnWkiaAGIy7xw1LH5tPl+Nelzk3TXb2yrONsvRq/rx3YxfqBCpeXnHBBAesL5KrOi5kU640NaQ5B2RubKX2lNOqu2Dzu1U+XiX97rHfXzDdYZMOAQ7BaB9/4liKvcee6QOR5LGeF6MHsfv92/HqH+bt2R/9yLxno64lB8fKikw37K8hZ4nQBUqVB44urXeSmZLpn1yL035LJeFpnIiUsFks6AQ0Ix7jHtaPp+qe9/5HpMikTWBAJS2+eut1SOmjbRMR5V2SWd5OIp9CpKZp1NlxuceuBgmPEOHrxxDYry7RdzsJsr53FCLf6Tw2oFI6dvHfu1ZYWVX7YZvoTyiC9PbYh36l1C7qr6FtvKcWcbmraoiwm2y+EK0v2ojYgg+gE="
