sudo: true
language: node_js
branches:
  only:
  - master
before_script:
- sudo apt-get install imagemagick
- sudo apt-get install graphicsmagick
- bash ./bin/prepare.sh
script:
- ls -al img/photo.jpg
after_success: bash ./bin/deploy.sh
env:
  global:
    secure: PRTnTWX8EDGjibIL/Q/S0b4xPdczAXuSBPNDz6DaG/2KXQ5ci/TWOpRmBNZQUdzfaf/1IdaxsDwFfcKq8mgBrPQrSKDkFFa8GHQh7DjCj2iPh81iqrbTO13yCSSJn88dWY8PghP1t35Qwowx34Cwuultw0F8pTkb0rU2cL4jS/Ez3sC4DUKhpXUpOy099QCyGutOTMFwgUcTpD6ZGZKlyeXOmJW0UC06ix1lWI7AFVbpiEsUY0psRIF/hFli4LTDLwSV/YQ3SQcgMDNGjVxDEN2EmVqMgiRWad6c4jIwuEE63qgHoyR1T6ui3XnsQLl1QaBr4JiGL90Qn+gvYkoGxDGL8JJwZP2e1fUeTz5AqTCe5Wd0utX1R/DS9T7wSTLti3MhyHSCiv/Z9z5AcuPOjHEp/J4aiMwp7mKQFzRri4ysCx292rmSrIbsdKcSdJ/9piDEW7rVT9K39CoAu2Jyc+CRVBeN2eL0FrYkYA6KCM5VlfeQgbjJByCusd8WSPyV/TuDLfj/p1oIKDC2yhuPftv7rqdAsplUJbLIcCMksYBbFru/h33UVAnsc6fcsyvZ1EiVv9XDcJqqtBqXGN/hMyyq0EwBHt0dWd9Re2qEThWIr3k0cTySy18pwO764oZxJJwAKRJVthn1dpwJAMunYZp2oNq0KJ035PY9xM5Zz9w=
