language: node_js

branches:
  only:
    - master

before_script: bash ./bin/prepare.sh

script:
    - ls -al img/photo.jpg

after_success: bash ./bin/deploy.sh

env:
  global:
  - GH_REF: github.com/miya0001/vrphoto.git
  - secure: "GahItDxrjjV5xHt7XU6mqDkNMVY/OBSy2Ebj86gxUG/2hwRJN07ftDeVe8jhzygq+nPHjtQhWLB3hj2T9njfhCR6GPQeHSy42VwhMZo/45HHXW3tt42646vWZVqaBZN0oLNfLtDA8YvtJIwiwhtcCYCkNcDhvPIqo2fKOwM2kcS3Gzpc3lT+hkKoOmm+JvdGsWjJj61ACDEKVJgX1a5L4DhnWMIOmyL1MyNX9PO+Kpgx8ZlrTMllFIEdgL1gVvKDTsJvjJX4rsMkoVDsSiG/YhIk47hmkTHU19IAgTmO8kcuH7aArjHcUQKDubLK4YHS+QEIeMSoQwCfYSbGwoGLI8KoQ55RWKq9J2j4xqT/kcDJpdv6//wIhyIQcWcrwR6FhroebJb+fzBBg6ielkY5pta0+WeR3eetpIRmqj2vb66Q//WKluCZh+CUKrkxkxV0JcPyM2q4eunr8WBtepfjLb5jBP61IDTvQEMFo1OlelP726r7J6qk9+9bXUD+SGf4C/bWJMAvLVmB9/m7FpvpBzgsRf2fXt+XhBpnA4I08UnUgkvdYKYVbX8mXHbXPSXEt7nQ0VzZ74qzpOvmYYh6YlXhZhc4avPAwNElb/2B7OEeETuUqroAbl9GlnVx+1UBB+ErqdniigNen6Gk4a4veWJ4f9MqjM1cW1blAZKKmh0="
